module.exports = {
  getFormNinePayment: async function (pool) {
    return new Promise((resolve, reject) => {
      var query = `SELECT 
                        SUM(lastBuildingTax) as lastBuildingTax,
                        SUM(currentBuildingTax) as currentBuildingTax,
                        SUM(totalBuildingTax) as totalBuildingTax, 
                        SUM(lastDivaTax) as lastDivaTax,
                        SUM(currentDivaTax) as currentDivaTax,
                        SUM(totalDivaTax) as totalDivaTax,
                        SUM(lastArogyaTax) as lastArogyaTax,
                        SUM(currentArogyaTax) as currentArogyaTax,
                        SUM(totalArogyaTax) as totalArogyaTax,
                        SUM(lastTaxFine) as lastTaxFine,
                        SUM(lastYearTaxFine) as lastYearTaxFine,
                        SUM(lastTaxRelief) as lastTaxRelief,
                        SUM(totalTax) as totalTax,
                        SUM(totalSampurnaTax) as totalSampurnaTax,
                        SUM(lastSpacialWaterTax) as lastSpacialWaterTax,
                        SUM(currentSpacialWaterTax) as currentSpacialWaterTax,
                        SUM(totalSpacialWaterTax) as totalSpacialWaterTax,
                        SUM(lastGenealWaterTax) as lastGenealWaterTax,
                        SUM(currentGenealWaterTax) as currentGenealWaterTax,
                        SUM(totalGenealWaterTax) as totalGenealWaterTax,
                        SUM(totalWaterTax) as totalWaterTax,
                        SUM(addToMagniLekh) as addToMagniLekh,
                        SUM(addNalBandNotice) as addNalBandNotice
                    FROM ps_form_nine_form`;
      pool.query(query, (error, result) => {
        if (error) {
          reject(error);
        } else {
          resolve(result);
        }
      });
    });
  },

  checkFilledDetails: function (pool, month, year) {
    return new Promise((resolve, reject) => {
      let query = `SELECT * FROM ps_kar_vasuli_avahal WHERE month = ? AND year = ?`;
      pool.query(query, [month, year], function (err, result) {
        err ? reject(err) : resolve(result);
      });
    });
  },

  getLastMonth: async function (pool) {
    return new Promise((resolve, reject) => {
      var query = `SELECT * FROM ps_kar_wasuli_ahawal ORDER BY id DESC LIMIT 1`;
      pool.query(query, (error, result) => {
        if (error) {
          reject(error);
        } else {
          resolve(result);
        }
      });
    });
  },

  getMonthwiseList: function (pool) {
    return new Promise((resolve, reject) => {
      let query = `SELECT month, year FROM ps_kar_vasuli_avahal ORDER BY month`;
      pool.query(query, function (err, result) {
        err ? reject(err) : resolve(result);
      });
    });
  },

  yearWiseList: function (pool, year) {
    return new Promise((resolve, reject) => {
      let query = `SELECT id, month, year FROM ps_kar_vasuli_avahal WHERE year = ? ORDER BY month`;
      pool.query(query, [year], function (err, result) {
        err ? reject(err) : resolve(result);
      });
    });
  },

  getPrintKarVasuli: function (pool, month, year) {
    return new Promise((resolve, reject) => {
      let query = `SELECT * FROM ps_kar_vasuli_avahal WHERE month = ? AND year = ?`;
      pool.query(query, [month, year], function (err, result) {
        err ? reject(err) : resolve(result);
      });
    });
  },

  postNewKarVasuliAvahal: function (pool, data) {
    return new Promise((resolve, reject) => {
      let query = `INSERT INTO ps_kar_vasuli_avahal
                            (
                            month,
                            year, 
                            totalDemandBuildingLast,
                            totalDemandBuildingCurrent,
                            totalDemandBuilding,
                            lastMonthRecoveryLast,
                            lastMonthRecoveryCurrent,
                            lastMonthRecoveryTotal,
                            currentMonthRecoveryLast,
                            currentMonthRecoveryCurrent,
                            currentMonthRecoveryTotal,
                            totalRecoveryRecoveryLast,
                            totalRecoveryRecoveryCurrent,
                            totalRecoveryRecoveryTotal,
                            totalRemainRecoveryLast,
                            totalRemainRecoveryCurrent,
                            totalRemainRecoveryTotal,
                            totalDemanDivaLast,
                            totalDemanDivaCurrent,
                            totalDemandDiva,
                            lastMonthDivaLast,
                            lastMonthDivaCurrent,
                            lastMonthDivaTotal,
                            currentMonthDivaLast,
                            currentMonthDivaCurrent,
                            currentMonthDivaTotal,
                            totalRecoveryDivaLast,
                            totalRecoveryDivaCurrent,
                            totalRecoveryDivaTotal,
                            totalRemainDivaLast,
                            totalRemainDivaCurrent,
                            totalRemainDivaTotal,
                            totalDemandArogyaLast,
                            totalDemandArogyaCurrent,
                            totalDemandArogya,
                            lastMonthArogyaLast,
                            lastMonthArogyaCurrent,
                            lastMonthArogyaTotal,
                            currentMonthArogyaLast,
                            currentMonthArogyaCurrent,
                            currentMonthArogyaTotal,
                            totalRecoveryArogyaLast,
                            totalRecoveryArogyaCurrent,
                            totalRecoveryArogyaTotal,
                            totalRemainArogyaLast,
                            totalRemainArogyaCurrent,
                            totalRemainArogyaTotal,
                            totalDemandOtherLast,
                            totalDemandOtherCurrent,
                            totalDemandOther,
                            lastMonthOtherLast,
                            lastMonthOtherCurrent,
                            lastMonthOtherTotal,
                            currentMonthOtherLast,
                            currentMonthOtherCurrent,
                            currentMonthOtherTotal,
                            totalRecoveryOtherLast,
                            totalRecoveryOtherCurrent,
                            totalRecoveryOtherTotal,
                            totalRemainOtherLast,
                            totalRemainOtherCurrent,
                            totalRemainOtherTotal,
                            totalDemandLast,
                            totalDemandCurrent,
                            totalDemandAll,
                            lastMonthTotalLast,
                            lastMonthTotalCurrent,
                            lastMonthAll,
                            currentMonthTotalLast,
                            currentMonthTotalCurrent,
                            currentMonthAll,
                            totalRecoveryTotalLast,
                            totalRecoveryTotalCurrent,
                            totalRecoveryAll,
                            totalRemainTotalLast,
                            totalRemainTotalCurrent,
                            totalRemainAll,
                            totalDemandGeneralWaterTaxLast,
                            totalDemandGeneralWaterTaxCurrent,
                            totalDemandGeneralTotalWaterTax,
                            lastMonthGeneralWaterTaxLast,
                            lastMonthGeneralWaterTaxCurrent,
                            lastMonthGeneralTotalWaterTax,
                            currentMonthGeneralWaterTaxLast,
                            currentMonthGeneralWaterTaxCurrent,
                            currentMonthGeneralTotalWaterTax,
                            totalRecoveryGeneralWaterTaxLast,
                            totalRecoveryGeneralWaterTaxCurrent,
                            totalRecoveryGeneralTotalWaterTax,
                            totalRemainGeneralWaterTaxLast,
                            totalRemainGeneralWaterTaxCurrent,
                            totalRemainGeneralTotalWaterTax,
                            totalDemandSpecialWaterTaxLast,
                            totalDemandSpecialWaterTaxCurrent,
                            totalDemandSpecialTotalWaterTax,
                            lastMonthSpecialWaterTaxLast,
                            lastMonthSpecialWaterTaxCurrent,
                            lastMonthSpecialTotalWaterTax,
                            currentMonthSpecialWaterTaxLast,
                            currentMonthSpecialWaterTaxCurrent,
                            currentMonthSpecialTotalWaterTax,
                            totalRecoverySpecialWaterTaxLast,
                            totalRecoverySpecialWaterTaxCurrent,
                            totalRecoverySpecialTotalWaterTax,
                            totalRemainSpecialWaterTaxLast,
                            totalRemainSpecialWaterTaxCurrent,
                            totalRemainSpecialTotalWaterTax,
                            totalDemandLastTotalWaterTax,
                            totalDemandCurrentTotalWaterTax,
                            totalDemandWaterTaxAll,
                            lastMonthLastTotalWaterTax,
                            lastMonthCurrentTotalWaterTax,
                            lastMonthWaterTaxAll,
                            currentMonthLastTotalWaterTax,
                            currentMonthCurrentTotalWaterTax,
                            currentMonthWaterTaxAll,
                            totalRecoveryLastTotalWaterTax,
                            totalRecoveryCurrentTotalWaterTax,
                            totalRecoveryWaterTaxAll,
                            totalRemainLastTotalWaterTax,
                            totalRemainCurrentTotalWaterTax,
                            totalRemainWaterTaxAll,
                            totalDemandLastABTotal,
                            totalDemandCurrentABTotal,
                            totalDemandAllAB,
                            lastMonthLastABTotal,
                            lastMonthCurrentABTotal,
                            lastMonthAllAB,
                            currentMonthLastABTotal,
                            currentMonthCurrentABTotal,
                            currentMonthAllAB,
                            totalRecoveryLastABTotal,
                            totalRecoveryCurrentABTotal,
                            totalRecoveryAllAB,
                            totalRemainLastABTotal,
                            totalRemainCurrentABTotal,
                            totalRemainAllAB,

                            buildingRecoveryPercentage,
                            divaRecoveryPercentage,
                            arogyaRecoveryPercentage,
                            otherRecoveryPercentage,
                            aRecoveryPercentage,
                            generalRecoveryPercentage,
                            specialRecoveryPercentage,
                            bRecoveryPercentage,
                            abRecoveryPercentage
                            )
                            VALUES (?)`;

      let insertArray = [
        data.month,
        data.year,
        data.totalDemandBuildingLast,
        data.totalDemandBuildingCurrent,
        data.totalDemandBuilding,
        data.lastMonthRecoveryLast,
        data.lastMonthRecoveryCurrent,
        data.lastMonthRecoveryTotal,
        data.currentMonthRecoveryLast,
        data.currentMonthRecoveryCurrent,
        data.currentMonthRecoveryTotal,
        data.totalRecoveryRecoveryLast,
        data.totalRecoveryRecoveryCurrent,
        data.totalRecoveryRecoveryTotal,
        data.totalRemainRecoveryLast,
        data.totalRemainRecoveryCurrent,
        data.totalRemainRecoveryTotal,
        data.totalDemanDivaLast,
        data.totalDemanDivaCurrent,
        data.totalDemandDiva,
        data.lastMonthDivaLast,
        data.lastMonthDivaCurrent,
        data.lastMonthDivaTotal,
        data.currentMonthDivaLast,
        data.currentMonthDivaCurrent,
        data.currentMonthDivaTotal,
        data.totalRecoveryDivaLast,
        data.totalRecoveryDivaCurrent,
        data.totalRecoveryDivaTotal,
        data.totalRemainDivaLast,
        data.totalRemainDivaCurrent,
        data.totalRemainDivaTotal,
        data.totalDemandArogyaLast,
        data.totalDemandArogyaCurrent,
        data.totalDemandArogya,
        data.lastMonthArogyaLast,
        data.lastMonthArogyaCurrent,
        data.lastMonthArogyaTotal,
        data.currentMonthArogyaLast,
        data.currentMonthArogyaCurrent,
        data.currentMonthArogyaTotal,
        data.totalRecoveryArogyaLast,
        data.totalRecoveryArogyaCurrent,
        data.totalRecoveryArogyaTotal,
        data.totalRemainArogyaLast,
        data.totalRemainArogyaCurrent,
        data.totalRemainArogyaTotal,
        data.totalDemandOtherLast,
        data.totalDemandOtherCurrent,
        data.totalDemandOther,
        data.lastMonthOtherLast,
        data.lastMonthOtherCurrent,
        data.lastMonthOtherTotal,
        data.currentMonthOtherLast,
        data.currentMonthOtherCurrent,
        data.currentMonthOtherTotal,
        data.totalRecoveryOtherLast,
        data.totalRecoveryOtherCurrent,
        data.totalRecoveryOtherTotal,
        data.totalRemainOtherLast,
        data.totalRemainOtherCurrent,
        data.totalRemainOtherTotal,
        data.totalDemandLast,
        data.totalDemandCurrent,
        data.totalDemandAll,
        data.lastMonthTotalLast,
        data.lastMonthTotalCurrent,
        data.lastMonthAll,
        data.currentMonthTotalLast,
        data.currentMonthTotalCurrent,
        data.currentMonthAll,
        data.totalRecoveryTotalLast,
        data.totalRecoveryTotalCurrent,
        data.totalRecoveryAll,
        data.totalRemainTotalLast,
        data.totalRemainTotalCurrent,
        data.totalRemainAll,
        data.totalDemandGeneralWaterTaxLast,
        data.totalDemandGeneralWaterTaxCurrent,
        data.totalDemandGeneralTotalWaterTax,
        data.lastMonthGeneralWaterTaxLast,
        data.lastMonthGeneralWaterTaxCurrent,
        data.lastMonthGeneralTotalWaterTax,
        data.currentMonthGeneralWaterTaxLast,
        data.currentMonthGeneralWaterTaxCurrent,
        data.currentMonthGeneralTotalWaterTax,
        data.totalRecoveryGeneralWaterTaxLast,
        data.totalRecoveryGeneralWaterTaxCurrent,
        data.totalRecoveryGeneralTotalWaterTax,
        data.totalRemainGeneralWaterTaxLast,
        data.totalRemainGeneralWaterTaxCurrent,
        data.totalRemainGeneralTotalWaterTax,
        data.totalDemandSpecialWaterTaxLast,
        data.totalDemandSpecialWaterTaxCurrent,
        data.totalDemandSpecialTotalWaterTax,
        data.lastMonthSpecialWaterTaxLast,
        data.lastMonthSpecialWaterTaxCurrent,
        data.lastMonthSpecialTotalWaterTax,
        data.currentMonthSpecialWaterTaxLast,
        data.currentMonthSpecialWaterTaxCurrent,
        data.currentMonthSpecialTotalWaterTax,
        data.totalRecoverySpecialWaterTaxLast,
        data.totalRecoverySpecialWaterTaxCurrent,
        data.totalRecoverySpecialTotalWaterTax,
        data.totalRemainSpecialWaterTaxLast,
        data.totalRemainSpecialWaterTaxCurrent,
        data.totalRemainSpecialTotalWaterTax,
        data.totalDemandLastTotalWaterTax,
        data.totalDemandCurrentTotalWaterTax,
        data.totalDemandWaterTaxAll,
        data.lastMonthLastTotalWaterTax,
        data.lastMonthCurrentTotalWaterTax,
        data.lastMonthWaterTaxAll,
        data.currentMonthLastTotalWaterTax,
        data.currentMonthCurrentTotalWaterTax,
        data.currentMonthWaterTaxAll,
        data.totalRecoveryLastTotalWaterTax,
        data.totalRecoveryCurrentTotalWaterTax,
        data.totalRecoveryWaterTaxAll,
        data.totalRemainLastTotalWaterTax,
        data.totalRemainCurrentTotalWaterTax,
        data.totalRemainWaterTaxAll,
        data.totalDemandLastABTotal,
        data.totalDemandCurrentABTotal,
        data.totalDemandAllAB,
        data.lastMonthLastABTotal,
        data.lastMonthCurrentABTotal,
        data.lastMonthAllAB,
        data.currentMonthLastABTotal,
        data.currentMonthCurrentABTotal,
        data.currentMonthAllAB,
        data.totalRecoveryLastABTotal,
        data.totalRecoveryCurrentABTotal,
        data.totalRecoveryAllAB,
        data.totalRemainLastABTotal,
        data.totalRemainCurrentABTotal,
        data.totalRemainAllAB,

        data.buildingRecoveryPercentage,
        data.divaRecoveryPercentage,
        data.arogyaRecoveryPercentage,
        data.otherRecoveryPercentage,
        data.aRecoveryPercentage,
        data.generalRecoveryPercentage,
        data.specialRecoveryPercentage,
        data.bRecoveryPercentage,
        data.abRecoveryPercentage,
      ];
      pool.query(query, [insertArray], function (err, result) {
        err ? reject(err) : resolve(result);
      });
    });
  },

  updateNewKarVasuliAvahal: function (pool, data) {
    return new Promise((resolve, reject) => {
      let query = `UPDATE ps_kar_vasuli_avahal
                           SET
                            month = ?,
                            year  = ?,
                            totalDemandBuildingLast  = ?,
                            totalDemandBuildingCurrent  = ?,
                            totalDemandBuilding  = ?,
                            lastMonthRecoveryLast  = ?,
                            lastMonthRecoveryCurrent  = ?,
                            lastMonthRecoveryTotal  = ?,
                            currentMonthRecoveryLast  = ?,
                            currentMonthRecoveryCurrent  = ?,
                            currentMonthRecoveryTotal  = ?,
                            totalRecoveryRecoveryLast  = ?,
                            totalRecoveryRecoveryCurrent  = ?,
                            totalRecoveryRecoveryTotal  = ?,
                            totalRemainRecoveryLast  = ?,
                            totalRemainRecoveryCurrent  = ?,
                            totalRemainRecoveryTotal  = ?,
                            totalDemanDivaLast  = ?,
                            totalDemanDivaCurrent  = ?,
                            totalDemandDiva  = ?,
                            lastMonthDivaLast  = ?,
                            lastMonthDivaCurrent  = ?,
                            lastMonthDivaTotal  = ?,
                            currentMonthDivaLast  = ?,
                            currentMonthDivaCurrent  = ?,
                            currentMonthDivaTotal  = ?,
                            totalRecoveryDivaLast  = ?,
                            totalRecoveryDivaCurrent  = ?,
                            totalRecoveryDivaTotal  = ?,
                            totalRemainDivaLast  = ?,
                            totalRemainDivaCurrent  = ?,
                            totalRemainDivaTotal  = ?,
                            totalDemandArogyaLast  = ?,
                            totalDemandArogyaCurrent  = ?,
                            totalDemandArogya  = ?,
                            lastMonthArogyaLast  = ?,
                            lastMonthArogyaCurrent  = ?,
                            lastMonthArogyaTotal  = ?,
                            currentMonthArogyaLast  = ?,
                            currentMonthArogyaCurrent  = ?,
                            currentMonthArogyaTotal  = ?,
                            totalRecoveryArogyaLast  = ?,
                            totalRecoveryArogyaCurrent  = ?,
                            totalRecoveryArogyaTotal  = ?,
                            totalRemainArogyaLast  = ?,
                            totalRemainArogyaCurrent  = ?,
                            totalRemainArogyaTotal  = ?,
                            totalDemandOtherLast  = ?,
                            totalDemandOtherCurrent  = ?,
                            totalDemandOther  = ?,
                            lastMonthOtherLast  = ?,
                            lastMonthOtherCurrent  = ?,
                            lastMonthOtherTotal  = ?,
                            currentMonthOtherLast  = ?,
                            currentMonthOtherCurrent  = ?,
                            currentMonthOtherTotal  = ?,
                            totalRecoveryOtherLast  = ?,
                            totalRecoveryOtherCurrent  = ?,
                            totalRecoveryOtherTotal  = ?,
                            totalRemainOtherLast  = ?,
                            totalRemainOtherCurrent  = ?,
                            totalRemainOtherTotal  = ?,
                            totalDemandLast  = ?,
                            totalDemandCurrent  = ?,
                            totalDemandAll  = ?,
                            lastMonthTotalLast  = ?,
                            lastMonthTotalCurrent  = ?,
                            lastMonthAll  = ?,
                            currentMonthTotalLast  = ?,
                            currentMonthTotalCurrent  = ?,
                            currentMonthAll  = ?,
                            totalRecoveryTotalLast  = ?,
                            totalRecoveryTotalCurrent  = ?,
                            totalRecoveryAll  = ?,
                            totalRemainTotalLast  = ?,
                            totalRemainTotalCurrent  = ?,
                            totalRemainAll  = ?,
                            totalDemandGeneralWaterTaxLast  = ?,
                            totalDemandGeneralWaterTaxCurrent  = ?,
                            totalDemandGeneralTotalWaterTax  = ?,
                            lastMonthGeneralWaterTaxLast  = ?,
                            lastMonthGeneralWaterTaxCurrent  = ?,
                            lastMonthGeneralTotalWaterTax  = ?,
                            currentMonthGeneralWaterTaxLast  = ?,
                            currentMonthGeneralWaterTaxCurrent  = ?,
                            currentMonthGeneralTotalWaterTax  = ?,
                            totalRecoveryGeneralWaterTaxLast  = ?,
                            totalRecoveryGeneralWaterTaxCurrent  = ?,
                            totalRecoveryGeneralTotalWaterTax  = ?,
                            totalRemainGeneralWaterTaxLast  = ?,
                            totalRemainGeneralWaterTaxCurrent  = ?,
                            totalRemainGeneralTotalWaterTax  = ?,
                            totalDemandSpecialWaterTaxLast  = ?,
                            totalDemandSpecialWaterTaxCurrent  = ?,
                            totalDemandSpecialTotalWaterTax  = ?,
                            lastMonthSpecialWaterTaxLast  = ?,
                            lastMonthSpecialWaterTaxCurrent  = ?,
                            lastMonthSpecialTotalWaterTax  = ?,
                            currentMonthSpecialWaterTaxLast  = ?,
                            currentMonthSpecialWaterTaxCurrent  = ?,
                            currentMonthSpecialTotalWaterTax  = ?,
                            totalRecoverySpecialWaterTaxLast  = ?,
                            totalRecoverySpecialWaterTaxCurrent  = ?,
                            totalRecoverySpecialTotalWaterTax  = ?,
                            totalRemainSpecialWaterTaxLast  = ?,
                            totalRemainSpecialWaterTaxCurrent  = ?,
                            totalRemainSpecialTotalWaterTax  = ?,
                            totalDemandLastTotalWaterTax  = ?,
                            totalDemandCurrentTotalWaterTax  = ?,
                            totalDemandWaterTaxAll  = ?,
                            lastMonthLastTotalWaterTax  = ?,
                            lastMonthCurrentTotalWaterTax  = ?,
                            lastMonthWaterTaxAll  = ?,
                            currentMonthLastTotalWaterTax  = ?,
                            currentMonthCurrentTotalWaterTax  = ?,
                            currentMonthWaterTaxAll  = ?,
                            totalRecoveryLastTotalWaterTax  = ?,
                            totalRecoveryCurrentTotalWaterTax  = ?,
                            totalRecoveryWaterTaxAll  = ?,
                            totalRemainLastTotalWaterTax  = ?,
                            totalRemainCurrentTotalWaterTax  = ?,
                            totalRemainWaterTaxAll  = ?,
                            totalDemandLastABTotal  = ?,
                            totalDemandCurrentABTotal  = ?,
                            totalDemandAllAB  = ?,
                            lastMonthLastABTotal  = ?,
                            lastMonthCurrentABTotal  = ?,
                            lastMonthAllAB  = ?,
                            currentMonthLastABTotal  = ?,
                            currentMonthCurrentABTotal  = ?,
                            currentMonthAllAB  = ?,
                            totalRecoveryLastABTotal  = ?,
                            totalRecoveryCurrentABTotal  = ?,
                            totalRecoveryAllAB  = ?,
                            totalRemainLastABTotal  = ?,
                            totalRemainCurrentABTotal  = ?,
                            totalRemainAllAB  = ?,

                            buildingRecoveryPercentage  = ?,
                            divaRecoveryPercentage  = ?,
                            arogyaRecoveryPercentage  = ?,
                            otherRecoveryPercentage  = ?,
                            aRecoveryPercentage  = ?,
                            generalRecoveryPercentage  = ?,
                            specialRecoveryPercentage  = ?,
                            bRecoveryPercentage  = ?,
                            abRecoveryPercentage = ?
                           
                            WHERE id = ?`;

                            
      let updateArray = [
        data.month,
        data.year,
        data.totalDemandBuildingLast,
        data.totalDemandBuildingCurrent,
        data.totalDemandBuilding,
        data.lastMonthRecoveryLast,
        data.lastMonthRecoveryCurrent,
        data.lastMonthRecoveryTotal,
        data.currentMonthRecoveryLast,
        data.currentMonthRecoveryCurrent,
        data.currentMonthRecoveryTotal,
        data.totalRecoveryRecoveryLast,
        data.totalRecoveryRecoveryCurrent,
        data.totalRecoveryRecoveryTotal,
        data.totalRemainRecoveryLast,
        data.totalRemainRecoveryCurrent,
        data.totalRemainRecoveryTotal,
        data.totalDemanDivaLast,
        data.totalDemanDivaCurrent,
        data.totalDemandDiva,
        data.lastMonthDivaLast,
        data.lastMonthDivaCurrent,
        data.lastMonthDivaTotal,
        data.currentMonthDivaLast,
        data.currentMonthDivaCurrent,
        data.currentMonthDivaTotal,
        data.totalRecoveryDivaLast,
        data.totalRecoveryDivaCurrent,
        data.totalRecoveryDivaTotal,
        data.totalRemainDivaLast,
        data.totalRemainDivaCurrent,
        data.totalRemainDivaTotal,
        data.totalDemandArogyaLast,
        data.totalDemandArogyaCurrent,
        data.totalDemandArogya,
        data.lastMonthArogyaLast,
        data.lastMonthArogyaCurrent,
        data.lastMonthArogyaTotal,
        data.currentMonthArogyaLast,
        data.currentMonthArogyaCurrent,
        data.currentMonthArogyaTotal,
        data.totalRecoveryArogyaLast,
        data.totalRecoveryArogyaCurrent,
        data.totalRecoveryArogyaTotal,
        data.totalRemainArogyaLast,
        data.totalRemainArogyaCurrent,
        data.totalRemainArogyaTotal,
        data.totalDemandOtherLast,
        data.totalDemandOtherCurrent,
        data.totalDemandOther,
        data.lastMonthOtherLast,
        data.lastMonthOtherCurrent,
        data.lastMonthOtherTotal,
        data.currentMonthOtherLast,
        data.currentMonthOtherCurrent,
        data.currentMonthOtherTotal,
        data.totalRecoveryOtherLast,
        data.totalRecoveryOtherCurrent,
        data.totalRecoveryOtherTotal,
        data.totalRemainOtherLast,
        data.totalRemainOtherCurrent,
        data.totalRemainOtherTotal,
        data.totalDemandLast,
        data.totalDemandCurrent,
        data.totalDemandAll,
        data.lastMonthTotalLast,
        data.lastMonthTotalCurrent,
        data.lastMonthAll,
        data.currentMonthTotalLast,
        data.currentMonthTotalCurrent,
        data.currentMonthAll,
        data.totalRecoveryTotalLast,
        data.totalRecoveryTotalCurrent,
        data.totalRecoveryAll,
        data.totalRemainTotalLast,
        data.totalRemainTotalCurrent,
        data.totalRemainAll,
        data.totalDemandGeneralWaterTaxLast,
        data.totalDemandGeneralWaterTaxCurrent,
        data.totalDemandGeneralTotalWaterTax,
        data.lastMonthGeneralWaterTaxLast,
        data.lastMonthGeneralWaterTaxCurrent,
        data.lastMonthGeneralTotalWaterTax,
        data.currentMonthGeneralWaterTaxLast,
        data.currentMonthGeneralWaterTaxCurrent,
        data.currentMonthGeneralTotalWaterTax,
        data.totalRecoveryGeneralWaterTaxLast,
        data.totalRecoveryGeneralWaterTaxCurrent,
        data.totalRecoveryGeneralTotalWaterTax,
        data.totalRemainGeneralWaterTaxLast,
        data.totalRemainGeneralWaterTaxCurrent,
        data.totalRemainGeneralTotalWaterTax,
        data.totalDemandSpecialWaterTaxLast,
        data.totalDemandSpecialWaterTaxCurrent,
        data.totalDemandSpecialTotalWaterTax,
        data.lastMonthSpecialWaterTaxLast,
        data.lastMonthSpecialWaterTaxCurrent,
        data.lastMonthSpecialTotalWaterTax,
        data.currentMonthSpecialWaterTaxLast,
        data.currentMonthSpecialWaterTaxCurrent,
        data.currentMonthSpecialTotalWaterTax,
        data.totalRecoverySpecialWaterTaxLast,
        data.totalRecoverySpecialWaterTaxCurrent,
        data.totalRecoverySpecialTotalWaterTax,
        data.totalRemainSpecialWaterTaxLast,
        data.totalRemainSpecialWaterTaxCurrent,
        data.totalRemainSpecialTotalWaterTax,
        data.totalDemandLastTotalWaterTax,
        data.totalDemandCurrentTotalWaterTax,
        data.totalDemandWaterTaxAll,
        data.lastMonthLastTotalWaterTax,
        data.lastMonthCurrentTotalWaterTax,
        data.lastMonthWaterTaxAll,
        data.currentMonthLastTotalWaterTax,
        data.currentMonthCurrentTotalWaterTax,
        data.currentMonthWaterTaxAll,
        data.totalRecoveryLastTotalWaterTax,
        data.totalRecoveryCurrentTotalWaterTax,
        data.totalRecoveryWaterTaxAll,
        data.totalRemainLastTotalWaterTax,
        data.totalRemainCurrentTotalWaterTax,
        data.totalRemainWaterTaxAll,
        data.totalDemandLastABTotal,
        data.totalDemandCurrentABTotal,
        data.totalDemandAllAB,
        data.lastMonthLastABTotal,
        data.lastMonthCurrentABTotal,
        data.lastMonthAllAB,
        data.currentMonthLastABTotal,
        data.currentMonthCurrentABTotal,
        data.currentMonthAllAB,
        data.totalRecoveryLastABTotal,
        data.totalRecoveryCurrentABTotal,
        data.totalRecoveryAllAB,
        data.totalRemainLastABTotal,
        data.totalRemainCurrentABTotal,
        data.totalRemainAllAB,

        data.buildingRecoveryPercentage,
        data.divaRecoveryPercentage,
        data.arogyaRecoveryPercentage,
        data.otherRecoveryPercentage,
        data.aRecoveryPercentage,
        data.generalRecoveryPercentage,
        data.specialRecoveryPercentage,
        data.bRecoveryPercentage,
        data.abRecoveryPercentage,
        data.id,
      ];
      pool.query(query, updateArray, function (err, result) {
        err ? reject(err) : resolve(result);
      });
    });
  },

  getPreviousKarVasuliAvahalData: function (pool, month, year) {
    return new Promise((resolve, reject) => {
      let query = `SELECT * FROM ps_kar_vasuli_avahal WHERE month = ? AND year = ?`;
      pool.query(query, [month, year], function (err, result) {
        err ? reject(err) : resolve(result);
      });
    });
  },

  existingEntriesExceptCurrentForMonthYear: function (pool, data) {
    return new Promise((resolve, reject) => {
      const query = `SELECT * FROM ps_kar_vasuli_avahal WHERE month = ? AND year = ? AND id != ?`;

      pool.query(query, [data.month, data.year, data.id], (err, result) => {
        err ? reject(err) : resolve(result);
      });
    });
  },
  deleteKarVasuli: function (pool, month, year) {
    return new Promise((resolve, reject) => {
      let query = `DELETE FROM ps_kar_vasuli_avahal WHERE month = ? AND year = ?`;
      pool.query(query, [month, year], function (err, result) {
        err ? reject(err) : resolve(result);
      });
    });
  },

  getKarVasuliDataVyId: function (pool, id) {
    return new Promise((resolve, reject) => {
      let query = `SELECT * FROM ps_kar_vasuli_avahal WHERE id =?`;
      pool.query(query, [id], function (err, result) {
        err ? reject(err) : resolve(result);
      });
    });
  },
};
